### PR TITLE
Correctly set address length in arp frames

### LINKED ISSUE #2314: Fail to open firefox in firejail: Error send: arp.c:182 arp_check: Invalid argument
Hello, this happened after upgrading the kernel from 4.19.12 to 4.20.0. Full output is below and I have no idea where even to start looking (same thing happens with apparmor disabled):

----

 firejail --x11=xephyr --apparmor --name=firefox --net=br10 --profile=/etc/firejail/firefox.profile openbox --startup /usr/lib64/firefox/firefox

*** Starting xephyr server: "Xephyr" "-ac" "-br" "-noreset" "-screen" "800x600" "-title" "firejail x11 sandbox" "-resizeable" ":363" ***

The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
Errors from xkbcomp are not fatal to the X server

*** Attaching to Xephyr display 363 ***

Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox.local
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Error send: arp.c:182 arp_check: Invalid argument

### PR DESCRIPTION
**Pull request by NickMolloy**
Kernel commit [99137b7](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=99137b7888f4058087895d035d81c6b2d31015c5) introduced an additional check of the address
length. This exposed a bug in the arp code where the address length was
being set incorrectly.
Now the length is set from the `ETH_ALEN` constant declared in
`linux/if_ether.h`.

This fixes #2314

### CODE REVIEW

**Comment by greencopper** [comment]
We need to have this merged asap.

**Comment by moviuro** [comment]
Tried it on Archlinux with kernel 4.20.0, all good :+1:

**Comment by netblue30** [comment]
Thanks for the fix, I'll make sure it goes on all our branches.

**Comment by greencopper** [comment]
Thanks! Great work!

File: src/firejail/arp.c [hunk 1]
```diff
@@ -78,7 +78,7 @@ void arp_announce(const char *dev, Bridge *br) {
 		errExit("if_nametoindex");
 	addr.sll_family = AF_PACKET;
 	memcpy (addr.sll_addr, ifr.ifr_hwaddr.sa_data, 6);
```
Comment (minus7) [inline src/firejail/arp.c]: Is it fine to keep the hardcoded `6` here?
